### ISSUE TITLE
Search results not updating when deleting characters

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#167]
When you carry out a search, the results reflect the search as it you type.

When you delete characters the same should be true.

**Comment by nemanjaglumac** [comment]
I'm on it. 
Fixed the bug last night, but I am still looking into other parts of the app. 
Namely, running the linter changed whitespace in more than 10 documents, which means it should probably be set with more strict rules. 
I can commit with whitespace ignored, but it would probably be good idea to make uniform rules for `Prettier` and `eslint` so that you avoid similar situations for future contributors.

**Comment by lmcjt37** [comment]
The linting is performed in the CI, which isn't correct IMO. There is another ticket to move the linting to a pre-commit hook and remove the eslint override - #136

**Comment by nemanjaglumac** [comment]
So, I can simply push only the file(s) where I have made changes if that's ok with you? 
After that, let's focus on setting the linters correctly.

**Comment by lmcjt37** [comment]
Sure 👍

**Comment by lmcjt37** [comment]
@nemanjaglumac closing as this is fixed via #172 

Linting fixes are for ticket - #136
